# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, stable, system-definition, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/04006c19-0550-43e9-b1c8-4fbc826550dc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-64d143dc-eb46-44a3-b4ee-a718c67e9d65".device = "/dev/disk/by-uuid/64d143dc-eb46-44a3-b4ee-a718c67e9d65";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/07AB-9B6E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/PNY-CS900-120GB" =
  { device = "/dev/disk/by-uuid/dacdfec7-f091-4a24-9789-41d9ab4f505d";
    fsType = "btrfs";
    options = [ "users" "nofail" ]; 
  };

  systemd.services.chown-pny-cs900-120gb = {
    description = "Change ownership of /mnt/PNY-CS900-120GB to the user";
    after = [ "mnt-PNY\x2dCS900\x2d120GB.mount" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${system-definition.coreutils}/bin/chown -R exil0681:users /mnt/PNY-CS900-120GB";
    };
  };

  fileSystems."/mnt/TOSHIBA-MQ04ABF100-1TB" =
  { device = "/dev/disk/by-uuid/7b4b5e46-bb46-4b49-a24f-a914ee9e6f50";
    fsType = "btrfs";
    options = [ "users" "nofail" ]; 
  };

  systemd.services.chown-toshiba-mq04abf100-1tb = {
    description = "Change ownership of /mnt/TOSHIBA-MQ04ABF100-1TB to the user";
    after = [ "mnt-TOSHIBA\x2dMQ04ABF100\x2d1TB.mount" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${system-definition.coreutils}/bin/chown -R exil0681:users /mnt/TOSHIBA-MQ04ABF100-1TB";
    };
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/18c21d2c-be8d-43af-a560-79aedb126c5b"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
