keys:
  - &primary age1tlk0wm79d9fatpyf2fv72wttlk9umck52hltparg5wuc7rzh0a7q2eg7kg
creation_rules:
  - path_regex: secrets/[^/]+/[^/]+\.yaml$|secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *primary